[build]
  base = "/"
  command = "yarn build"
  publish = "site/public"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.19.1"

[[redirects]]
  from = "/wedstrijdverslagen"
  to = "/tag/wedstrijdverslag"
  status = 301
  force = false
