[build]
  base = "/"
  command = "yarn build"
  publish = "site/public"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.19.1"

[[redirects]]
  from = "/nieuws"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/blog/thb-moc17-21-09-19"
  to = "/nieuws/19-20/thb-moc17-openingswedstrijd"
  status = 301
[[redirects]]
  from = "/blog/19-20-eerste-aanwinst-hala3"
  to = "/nieuws/19-20/eerste-aanwinst-hala3"
  status = 301
[[redirects]]
  from = "/blog/19-20-zoektocht-nieuwe-keeper"
  to = "/nieuws/19-20/zoektocht-nieuwe-keeper"
  status = 301
