media_folder: "assets/images/uploads"
public_folder: "uploads"
logo_url: "https://www.hala3.nl/images/thb-icon.png"

backend:
  name: git-gateway
  branch: master

collections:
  - name: "blog"
    label: "Blog"
    folder: "contents/nl/blog"
    create: true
    identifier_field: name
    fields:
      - {label: "Naam van bestand", name: "name", widget: "string"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "year", widget: "string"}
      - {label: "Afbeelding", name: "thumbnail", widget: "image"}
      - {label: "Beschrijving (1 a 2 regels)", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
